# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:

  - name: Resume
    url: author/xie-wei-谢威/
    weight: 20
  - name: Member
    url: people
    weight: 30
  - name: Publications
    url: publication
    weight: 40
  - name: Research
    url: research
    weight: 50
  - name: Robots
    url: robot
    weight: 60
  - name: Contact
    url: contact
    weight: 70
